Update codecov config to match its config in the ui
hms-dbmi-cellenics/api pull request #179
Opened 2021-07-15 23:45 UTC by cosa65

# Background
#### Link to issue 
https://biomage.atlassian.net/browse/BIOMAGE-1102

#### Link to staging deployment URL 

#### Links to any Pull Requests related to this

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock (with latest production data downloaded with biomage experiment pull)
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

2021-07-15 23:46 UTC, cosa65 commented
For context on the changes performed here take a look at the (resolved) points proposed by pol at https://github.com/biomage-ltd/ui/pull/393

2021-07-16 08:40 UTC, kafkasl requested changes

2021-07-16 08:40 UTC, kafkasl commented on codecov.yaml
> +        # this allows a 10% drop from the previous base commit coverage
allows a 5% haha

2021-07-16 08:41 UTC, kafkasl approved these changes

2021-07-19 00:53 UTC, merged