Update openapi validator from v3 to v4
hms-dbmi-cellenics/api pull request #39
Opened 2021-01-20 16:06 UTC by cosa65

# Background
The open api validator is causing problems when receiving requests from the ui by returning the following error: 
`Bad Request: request should have required property 'headers'' error` 

Based on the issue in https://github.com/cdimascio/express-openapi-validator/issues/516 , updating to v4 causes the error to no longer appear.

#### Link to issue 

#### Link to staging deployment URL 

#### Links to any Pull Requests related to this

#### Anything else the reviewers should know about the changes here

# Changes
### Code changes

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [ ] Photo of a cute animal attached to this PR

2021-01-20 17:28 UTC, marcellp commented
Did this not change anything in `package-lock.json`?

2021-01-20 17:46 UTC, cosa65 commented
> Did this not change anything in `package-lock.json`?

Just updated and added the package-lock

2021-01-21 11:03 UTC, marcellp approved these changes

2021-01-21 13:15 UTC, marcellp requested changes
Please deploy a staging environment to make sure this works end-to-end.

2021-01-21 13:29 UTC, marcellp approved these changes
lgtm

2021-01-21 13:29 UTC, merged